DATABASE_HOST: "127.0.0.1"
DATABASE_PORT: "3306"
DATABASE_USER: "root"
DATABASE_PASS: "123456"
DATABASE_NAME: "react_app"
SMTP_HOST: "localhost:3000"
SMTP_ADDRESS: "smtp.gmail.com"
SMTP_PORT: "587"
SMTP_EMAIL: "khanhdong95vip@gmail.com"
SMTP_PASSWORD: "nwxblouugfoknjun"
SMTP_DOMAIN: "gmail.com"
ADMIN_EMAIL: "khanhdong95vip@gmail.com"
INSTAGRAM_TOKEN: "7982311474.6927e20.96fa829cde234a46b95616adced484c1"
INSTAGRAM_CLIENT_ID: "6927e20cae624ee98b327ed4e5bba141"
INSTAGRAM_CLIENT_SECRET: "6978e314a0f64ece9c4a18b9eceba78c"
INSTAGRAM_USER_ID: "7982311474"
TIME_ZONE: "Asia/Ho_Chi_Minh"
