default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV["DATABASE_NAME"] %>
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASS"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  port:  <%= ENV["DATABASE_PORT"] %>

development:
  <<: *default
  database: "react_app_develop"

test:
  <<: *default
  database: "react_app_test"

production:
  <<: *default
